import Head from "next/head";
import * as Styles from '../styles/home'
import SearchSection from "../components/SearchSection";
import LostItemsSection from "../components/ItemsSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Styles.Wrapper>
        <Styles.LogoWrapper>
          <Styles.LogoImage src="/logo.png"></Styles.LogoImage>
        </Styles.LogoWrapper>
        <SearchSection />
        <LostItemsSection />
      </Styles.Wrapper>
    </>
  );
}
