import Head from "next/head";
import * as Styles from "../components/Home/homeStyle.js"
import HomeSection from "../components/Home/homeComponent.js";
import SearchSection from "../components/Search/SearchSectionComponent.js";
import LostItemsSection from "../components/Items/ItemSection.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>FAIND</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <Styles.Wrapper>
        <HomeSection />

        <SearchSection />
        
        <LostItemsSection />
      </Styles.Wrapper>
      
    </>
  );
}
